services:
  - type: web
    name: restobar-api
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 3000 